version: 2.1

parameters:
  node-version:
    type: string
    default: '22.11.0'

jobs:
  checks:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - run: yarn install --immutable
      - run: yarn npm audit --recursive --severity critical
      - run: yarn dedupe --check
      - run: yarn svg:check

workflows:
  checks:
    jobs:
      - checks
